### PR TITLE
MNT: Re-rendered with conda-smithy 2.1.1

### PR DESCRIPTION
**Pull request by lexual**

### CODE REVIEW

**Comment by jakirkham** [comment]
While we can merge this, `pep8` has been superseded by `pycodestyle`. So I'd recommend switching to that if possible.

**Comment by lexual** [comment]
OK, wasn't aware.
Should this become a metapackage that installs pycodestyle for a while perhaps?

**Comment by jakirkham** [comment]
I don't think so. Packages that require `pep8` still expect that namespace. So switching it to a metapackage will likely break packages reliant on `pep8`.

That said, I'm happy to merge this. Just trying to give you some context.

**Comment by lexual** [comment]
should we change all packages that depend upon pep8 to now depend on pycodestyle?

**Comment by jakirkham** [comment]
Only once upstream changes them for the same reason as above.

Though it might be worth letting upstream devs know about this change if they haven't already switched in their development branch.

**Pull request merged**
